module.exports = {
  mode: 'jit',
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    safeList: [],
    content: ['./index.html', './src/**/*.tsx', './src/**/*.ts'],
  },
  theme: {
    screens: {
      mobile: { min: '300px', max: '500px' },
      laptop: '1024px',
      desktop: '1280px',
      lg: '1280px',
    },
    // minWidth: {
    //   40: '10rem',
    //   60: '15rem',
    //   80: '20rem',
    //   100: '25rem',
    // },
    // maxWidth: {
    //   120: '30rem',
    //   160: '40rem',
    //   200: '50rem',
    // },
  },
  variants: {},
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        mytheme: {
          primary: '#F1A81B',
          secondary: '#3F6600',
          accent: '#3F6600',
          neutral: '#0E5011',
          'base-100': '#FFFFFF',
          info: '#3ABFF8',
          success: '#36D399',
          warning: '#FBBD23',
          error: '#F87272',
        },
      },
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
    ],
  },
};
